# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B6xM9N0COutiJ5Vmpgv0B4450M7xB_jW

Gioncarlo Sebastian Sijabat
255150200111017
"""

import matplotlib.pyplot as plt

x = [8,7,6,5,4,9,7,6,5,4]
y = [15,20,25,30,35,10,22,27,33,38]
xtotal = 0
ytotal = 0

# Jumlah X
print("X = ",x)
for i in x:
  xtotal += i
print("Sigma X = ",xtotal)
print("")

# Jumlah Y
print("Y = ",y)
for i in y:
  ytotal += i
print("Sigma Y = ",ytotal)
print("")

# Jumlah X^2
xkuad = []
xkuadtotal = 0
for i in x:
  xkuad.append(i**2)
print("X^2 = ",xkuad)
for i in xkuad:
  xkuadtotal += i
print("Sigma X^2 = ",xkuadtotal)
print("")

# Jumlah XY
xy = [x*y for x,y in zip(x,y)]
print("XY = ",xy)
xytotal = 0
for i in xy:
  xytotal += i
print("Sigma XY = ",xytotal)
print("")

# Persamaan Regresi
b = (10*xytotal-xtotal*ytotal)/(10*xkuadtotal-(xtotal)**2)
a = (ytotal-b*xtotal)/10

bround = round(b,2)
around = round(a,2)

print("a =",around)
print("b =",bround)
print("Y =",around,"+",bround,"X")
print(" ")

# Grafik Regresi
plt.scatter(x,y)
plt.xlabel('Jam Tidur')
plt.ylabel('Pengeluaran Kopi')
plt.title('Apakah Waktu Tidur Mempengaruhi Jumlah Uang yang Dihabiskan untuk Kopi?')
plt.show()